// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnxEkxsQcgtr7YE0lPFoekX22sgSIhXk',
    appId: '1:976829837125:web:30a9fe268c689f8499182c',
    messagingSenderId: '976829837125',
    projectId: 'lastnyam-message',
    authDomain: 'lastnyam-message.firebaseapp.com',
    storageBucket: 'lastnyam-message.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAgyyEgE98dJ3LkWNygNnf9PPFxS0y-vA',
    appId: '1:976829837125:android:25a1a1fabf38271099182c',
    messagingSenderId: '976829837125',
    projectId: 'lastnyam-message',
    storageBucket: 'lastnyam-message.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cNMNIcV17AsdcOXBcwdg6ZwWaDkLkhM',
    appId: '1:976829837125:ios:553facf0c4a421ab99182c',
    messagingSenderId: '976829837125',
    projectId: 'lastnyam-message',
    storageBucket: 'lastnyam-message.firebasestorage.app',
    iosBundleId: 'com.example.lastNyam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_cNMNIcV17AsdcOXBcwdg6ZwWaDkLkhM',
    appId: '1:976829837125:ios:553facf0c4a421ab99182c',
    messagingSenderId: '976829837125',
    projectId: 'lastnyam-message',
    storageBucket: 'lastnyam-message.firebasestorage.app',
    iosBundleId: 'com.example.lastNyam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASnxEkxsQcgtr7YE0lPFoekX22sgSIhXk',
    appId: '1:976829837125:web:7f31adeac03d5e6599182c',
    messagingSenderId: '976829837125',
    projectId: 'lastnyam-message',
    authDomain: 'lastnyam-message.firebaseapp.com',
    storageBucket: 'lastnyam-message.firebasestorage.app',
  );

}